blueprint:
  name: Hydro-Quebec Winter Credit
  description: '# Gestion des événements de crédit hivernal d''Hydro-Québec.


    Ce blueprint offre les bases pour faire la gestion des événements de pointes critiques
    dans le cadre du programme de [crédit hivernal d''Hydro-Québec](https://www.hydroquebec.com/residentiel/espace-clients/tarifs/option-credit-hivernal.html).
    Il a été créé pour fonctionner avec le projet [Hydroqc](https://hydroqc.ca) qui
    extrait les données de votre compte à partir du portail client d''Hydro-Québec.


    ## Configuration


    ### Entités de temps et de criticité de la période.

    Les valeurs des premières configurations seront autoremplies si le nom de votre
    contrat dans votre configuration hydroqc est "maison". Autrement vous devrez sélectionner
    les entités correspondantes.


    ### Actions


    Définition des actions à effectuer dans Home-Assistant lors de chaque début et
    fin de périodes.


    Vous trouverez plus de détail sur les logiques applicables pour les crédits hivernaux
    dans notre [documentation](https://hydroqc.ca/fr/docs/winter-credits/).

    '
  domain: automation
  input:
    peak_active_AM:
      name: Capteur binaire - Pointe du matin
      description: Capteur indiquant si une pointe critique du matin est en cours.
      default: binary_sensor.peak_today_AM
      selector:
        entity:
          domain: binary_sensor
    peak_active_PM:
      name: Capteur binaire - Pointe du soir
      description: Capteur indiquant si une pointe critique du soir est en cours.
      default: binary_sensor.peak_today_PM
      selector:
        entity:
          domain: binary_sensor
    preheat_active:
      name: Capteur binaire - Pré-chauffage en cours
      description: Capteur indiquant si le préchauffage est en cours.
      default: binary_sensor.preheat_active
      selector:
        entity:
          domain: binary_sensor
    pre_heat_start_action:
      name: Action de préchauffage
      description: Actions à effectuer avant la période de pointe critique.
      default: []
      selector:
        action: {}
    critical_peak_start_action_AM:
      name: Action début pointe critique (Matin)
      description: Actions à effectuer au début de la période de pointe critique du matin.
      default: []
      selector:
        action: {}
    critical_peak_start_action_PM:
      name: Action début pointe critique (Soir)
      description: Actions à effectuer au début de la période de pointe critique du soir.
      default: []
      selector:
        action: {}
    critical_peak_end_action_AM:
      name: Action fin pointe critique (Matin)
      description: Actions à effectuer à la fin de la période de pointe critique du matin.
      default: []
      selector:
        action: {}
    critical_peak_end_action_PM:
      name: Action fin pointe critique (Soir)
      description: Actions à effectuer à la fin de la période de pointe critique du soir.
      default: []
      selector:
        action: {}
mode: parallel
trigger:
  - platform: state
    entity_id: !input preheat_active
    from: 'off'
    to: 'on'
    id: preheat_start_trigger
  - platform: state
    entity_id: !input peak_active_AM
    from: 'off'
    to: 'on'
    id: peak_start_trigger_AM
  - platform: state
    entity_id: !input peak_active_PM
    from: 'off'
    to: 'on'
    id: peak_start_trigger_PM
  - platform: state
    entity_id: !input peak_active_AM
    from: 'on'
    to: 'off'
    id: peak_end_trigger_AM
  - platform: state
    entity_id: !input peak_active_PM
    from: 'on'
    to: 'off'
    id: peak_end_trigger_PM
action:
  - choose:
      - conditions:
          - condition: trigger
            id: preheat_start_trigger
        sequence: !input pre_heat_start_action
      - conditions:
          - condition: trigger
            id: peak_start_trigger_AM
        sequence: !input critical_peak_start_action_AM
      - conditions:
          - condition: trigger
            id: peak_start_trigger_PM
        sequence: !input critical_peak_start_action_PM
      - conditions:
          - condition: trigger
            id: peak_end_trigger_AM
        sequence: !input critical_peak_end_action_AM
      - conditions:
          - condition: trigger
            id: peak_end_trigger_PM
        sequence: !input critical_peak_end_action_PM
