blueprint:
  name: Hydro-Québec Crédits Hivernaux
  description: 'Gestion des événements de crédit hivernal Hydro-Québec.'
  domain: automation
  input:
    peak_active:
      name: Pointe en cours (critique)
      description: Indicateur de pointe critique active
      default: binary_sensor.hydropeak_cpc_d_peak_active
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    preheat_active:
      name: Pré-chauffage en cours
      description: Indicateur de préchauffage actif
      default: binary_sensor.hydropeak_cpc_d_preheat_active
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    peak_today_AM:
      name: Pointe Matin Aujourd'hui
      default: binary_sensor.hydropeak_cpc_d_peak_today_am
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    peak_tomorrow_AM:
      name: Pointe Matin Demain
      default: binary_sensor.hydropeak_cpc_d_peak_tomorrow_am
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    peak_today_PM:
      name: Pointe Soir Aujourd'hui
      default: binary_sensor.hydropeak_cpc_d_peak_today_pm
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    peak_tomorrow_PM:
      name: Pointe Soir Demain
      default: binary_sensor.hydropeak_cpc_d_peak_tomorrow_pm
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    anchor_start:
      name: Début de l'ancrage
      default: sensor.hydropeak_cpc_d_anchor_start
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    anchor_end:
      name: Fin de l'ancrage
      default: sensor.hydropeak_cpc_d_anchor_end
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    event_start:
      name: Début de l'événement
      default: sensor.hydropeak_cpc_d_event_start
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    event_end:
      name: Fin de l'événement
      default: sensor.hydropeak_cpc_d_event_end
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    preheat_start:
      name: Début du préchauffage
      default: sensor.hydropeak_cpc_d_preheat_start
      selector:
        entity:
          domain:
          - sensor
          multiple: false
  source_url: https://raw.githubusercontent.com/devsforges/WinterCreditBlueprint/main/hq_winter_credit/WinterCreditBlueprint.yaml
mode: parallel
trigger:
- platform: state
  entity_id: !input preheat_active
  from: 'off'
  to: 'on'
  id: preheat_trigger
- platform: state
  entity_id: !input peak_active
  from: 'off'
  to: 'on'
  id: peak_start_trigger
- platform: state
  entity_id: !input peak_active
  from: 'on'
  to: 'off'
  id: peak_end_trigger
- platform: state
  entity_id: !input peak_today_AM
  from: 'off'
  to: 'on'
  id: anchor_start_trigger
- platform: state
  entity_id: !input peak_today_PM
  from: 'off'
  to: 'on'
  id: anchor_start_trigger
- platform: state
  entity_id: !input peak_tomorrow_AM
  from: 'off'
  to: 'on'
  id: anchor_start_trigger
- platform: state
  entity_id: !input peak_tomorrow_PM
  from: 'off'
  to: 'on'
  id: anchor_start_trigger
- platform: state
  entity_id: !input preheat_active
  from: 'on'
  to: 'off'
  id: anchor_end_trigger
- platform: state
  entity_id: !input anchor_start
  id: anchor_start_trigger
- platform: state
  entity_id: !input anchor_end
  id: anchor_end_trigger
- platform: state
  entity_id: !input event_start
  id: event_start_trigger
- platform: state
  entity_id: !input event_end
  id: event_end_trigger
- platform: state
  entity_id: !input preheat_start
  id: preheat_start_trigger
